export function fetchInventoryByIds(callback) {
  // Rather than immediately returning, we delay our code with a timeout to simulate asynchronous behavior 
  setTimeout(() => {
    callback({
      NewSingleGoodsData : {
        object_list: [{
          "goodsData": [{
            "id": 9528,
            "agreement": "",
            "count": 10,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/18/20160418161827_xATJW.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102274,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 锖浅葱",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：148×108×17mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 61,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/20/20160420113724_an4rs.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 10,
            "url": "/buy/item/detail/?id=9528&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9529,
            "agreement": "",
            "count": 9,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/18/20160418161845_LFSX4.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102275,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 松巧色",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：148×108×17mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 50,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "related_blogs": [],
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/item/201604/20/20160420153655_Qcwat.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 11,
            "url": "/buy/item/detail/?id=9529&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9530,
            "agreement": "",
            "count": 10,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/18/20160418161901_TfYit.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102276,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 浅贻",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：148×108×17mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 49,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/18/20160418184250_hFSGw.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 13,
            "url": "/buy/item/detail/?id=9530&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9531,
            "agreement": "",
            "count": 9,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/18/20160418161918_juszV.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102277,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 江户钳",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：148×108×17mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 50,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/18/20160418183213_yekcM.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 9,
            "url": "/buy/item/detail/?id=9531&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9532,
            "agreement": "",
            "count": 13,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/18/20160418164241_kSyGc.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102278,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 珊瑚梅",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：148×108×17mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 61,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/18/20160418185059_43WNx.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 10,
            "url": "/buy/item/detail/?id=9532&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9533,
            "agreement": "",
            "count": 10,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/18/20160418161935_LsGHX.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102279,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 菖蒲",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：148×108×17mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 49,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/18/20160418184250_hFSGw.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 11,
            "url": "/buy/item/detail/?id=9533&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9534,
            "agreement": "",
            "count": 15,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/18/20160418162003_SWBdZ.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102280,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 苏红梅",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：148×108×17mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 50,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/20/20160420113544_UsaRH.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 12,
            "url": "/buy/item/detail/?id=9534&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9535,
            "agreement": "",
            "count": 9,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/18/20160418162101_fFcBx.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102281,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 桑染",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：148×108×17mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 49,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/18/20160418164911_SCVWn.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 13,
            "url": "/buy/item/detail/?id=9535&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9536,
            "agreement": "",
            "count": 5,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/18/20160418162132_HzCnF.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102283,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 阿多诺斯",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：148×108×17mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 60,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/18/20160418164655_sCyvu.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 9,
            "url": "/buy/item/detail/?id=9536&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9537,
            "agreement": "",
            "count": 9,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/20/20160420134150_imxau.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102294,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 玉蜀黍",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：148×108×17mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 50,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/20/20160420134644_RwBCy.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 10,
            "url": "/buy/item/detail/?id=9537&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9538,
            "agreement": "",
            "count": 10,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/20/20160420134211_AscNT.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161739_AFNLR.jpeg", "http://img4q.duitang.com/uploads/people/201604/18/20160418161758_xKTkc.jpeg"],
            "status": "0",
            "recommend": "本子是裸背装订，没有胶装，所以内页尽量不要裁开，会带动其他纸页掉下来。\n空白页，有特殊书写要求的要注意内页的排版风格。\n纸张有一定的韧性，厚度适中，墨会极少量的随纸张表面的纤维外散。\n如果一定要用钢笔书写，建议选择出水量较少或笔尖较细的纸张用水笔书写。",
            "spu_id": 102295,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "福铺碎花布手帐笔记本 藤纳户",
            "inventory_desc": "碎花布面的封面设计，复古又小清新。内页是白色的空白纸张，可以随时随地写写画画，裸背装订能够完全平摊，书写更自由，不束缚你任何一点创作灵感。拿来做手账也是非常合适。92g的轻型纸，148×108×17mm的尺寸，A4纸张的四分之一，让你轻松携带，完全不怕放在包包里重到崩溃。轻归轻，纸张的优秀质感却未被改变，页面平滑、色泽舒适、不渗墨，即使是配合日常的办公笔都能带来极佳的书写体验。福铺特别采用特有的白盒包装，硬挺的纸质提升整本本子的层次，拿在手中更是尽显品味。",
            "inventory_cat": "笔记本",
            "inventory_attr": "品牌: 福铺\n品类：笔记本\n材质：内页92克优质书纸/封面硬面抄/扉页150克特种纸\n页数：144页\n尺寸：220x150x30mm\n产地: 中国\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 60,
            "buy_limit": 10,
            "market_price": 35,
            "sale_price": 28,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/20/20160420134659_whrXT.jpeg"],
            "inventory_caption": "不能割舍的手账本",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 28,
            "zc_promotions": [],
            "left_percent": 11,
            "url": "/buy/item/detail/?id=9538&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9526,
            "agreement": "",
            "count": 5,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/25/20160425171849_tJBLE.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/25/20160425163447_3nZHU.jpeg", "http://img4q.duitang.com/uploads/people/201604/25/20160425163501_jiMrN.jpeg", "http://img4q.duitang.com/uploads/people/201604/25/20160425171743_GaXkB.jpeg", "http://img4q.duitang.com/uploads/people/201604/25/20160425163523_rAYvz.jpeg", "http://img4q.duitang.com/uploads/people/201604/25/20160425163535_ifjsh.jpeg"],
            "status": "0",
            "recommend": "使用前将笔头前的蜡封取下。\n使用后记得将笔弹回，防止笔头干涸造成下次书写不流畅。",
            "spu_id": 102272,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "PILOT百乐Juice系列0.5mm中性笔 黑色+蓝色+红色+蓝黑+浅蓝",
            "inventory_desc": "百乐果汁色中性笔是百乐家的新品。采用颜料墨水，色彩相当艳丽，防水耐光不断墨，具有很好的保存性。笔杆采用环保材料制成，别看是塑料的笔杆，其实用料还是很扎实，握杆带点状防滑握胶，握起来一点都不膈手，握久了手也不会痛，符合人体工学，书写舒适。活动式大角度笔夹，携带更方便，到哪都能带着。",
            "inventory_cat": "文具",
            "inventory_attr": "品牌：PILOT/百乐\n品类：中性笔\n材质：笔杆为车用ABS材质\n书写粗细：0.5mm\n产地: 日本\n包装：有盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 67,
            "buy_limit": 10,
            "market_price": 88,
            "sale_price": 29,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/20/20160420151844_utABf.jpeg"],
            "inventory_caption": "手账必备气质笔",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 29,
            "zc_promotions": [],
            "left_percent": 14,
            "url": "/buy/item/detail/?id=9526&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }, {
            "id": 9527,
            "agreement": "",
            "count": 1,
            "valid": true,
            "pictures": ["http://img4q.duitang.com/uploads/people/201604/25/20160425162558_FsEzX.thumb.400_400_c.jpeg", "http://img4q.duitang.com/uploads/people/201604/25/20160425162613_jzfFt.jpeg", "http://img4q.duitang.com/uploads/people/201604/25/20160425162657_Tt34m.jpeg", "http://img5q.duitang.com/up"],
            "status": "0",
            "recommend": "可擦笔请勿用于考试、支票及有价证券等需要签名的重要文件，以免造成不必要的麻烦和损失。\n笔的尾部自带橡皮，随时都可擦拭，建议购买百乐专门的可擦笔橡皮，因为普通橡皮会擦不干净的。\n使用时笔芯不要按出过长，1mm左右最佳，防止书写时断裂。",
            "spu_id": 102273,
            "supplier_name": "堆糖商店",
            "supplier_id": "240",
            "inventory_name": "PILOT百乐可擦彩色自动铅笔 粉色笔+粉色笔芯",
            "inventory_desc": "学设计的小伙伴的救命稻草，手绘神器，彩色的铅笔芯超级赞，颜色美的根本放不下手。笔身设计超赞，整体使用效果非常舒适，长期书写也不会倦手。笔尖可以缩回，可以避免不必要的浪费。外观更是拯救无数颜控，外观超美，百看不厌，颜色很醒目。绘画、设计、画底稿都可以使用，错了可以擦掉，再也不用因为一笔画错而功亏一篑了。",
            "inventory_cat": "文具",
            "inventory_attr": "品牌：PILOT/百乐\n品类：自动铅笔\n规格：笔芯长度6cm/根 共6根\n材质：塑料\n书写粗细：0.7mm\n产地: 日本\n包装：无盒无塑封\n部分海外商品以批次区分，无保质期，堆糖只选择新鲜批次，请放心采购。",
            "sold_quantity": 113,
            "buy_limit": 10,
            "market_price": 45,
            "sale_price": 19.5,
            "batch_no": 20168888,
            "onsale_time": 1461549600000,
            "offsale_time": 1647828000000,
            "logistics_price": "¥6.00",
            "logistics_threshold": 88,
            "full_desc": "",
            "sale_stage": 1,
            "inventory_type": 1,
            "overseas_intro": "",
            "cart_available": 1,
            "delivery_type": 1,
            "banner_title": "",
            "banner_link": "",
            "detail_desc_pics": ["http://img4q.duitang.com/uploads/people/201604/20/20160420150839_SswVc.jpeg"],
            "inventory_caption": "铅笔也能鲜亮亮",
            "sec_killable": true,
            "flash_sale_valid": false,
            "origin_price": 19.5,
            "zc_promotions": [],
            "left_percent": 6,
            "url": "/buy/item/detail/?id=9527&__urlopentype=pageweb&goodfrom=hotSingleGoods"
          }],
          "bannerData": {
            "object_list": [{
              "target": "http://www.duitang.com/guide2/buy_group_purchase/2016042601/?__urlopentype=pageweb",
              "tag": "NEW",
              "stitle": "布艺随身手帐专场 >",
              "style": "",
              "content_type": "",
              "image_url": "http://img4q.duitang.com/uploads/people/201604/25/20160425142354_tFnhU.thumb.800_0.jpeg",
              "enabled_at": 1461636000,
              "enabled_at_str": "2016-04-26 10:00:00",
              "disabled_at": 1462154400,
              "disabled_at_str": "2016-05-02 10:00:00",
              "description": "带一本春意出发",
              "tag_title": "9528, 9529, 9530, 9531, 9532, 9533, 9534, 9535, 9536, 9537, 9538, 9526, 9527",
              "dynamic_info": "",
              "icon_url": ""
            }],
            "index": 0
          },
          "addTime": {
            "day": "星期二",
            "year": 2016,
            "mouth": 4,
            "date": 26
          }
        }],
        baba:[],
        ee: []
      } 
    });
  }, 500);

  // In the case of a real world API call, you'll normally run into a Promise like this:
  // API.getUser().then(user => callback(user));
}
